language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: KymgBnoq29aObD/lGQ4uIpo/3VNf5mx/UHBeMiQilgec8CHC2EQj2D+MMGNUCqh/+7wnKPNSru7BQe8MHgQc5eh3Rzq5bEkD9ojXI35xn1xBNWTFO/DTcjQwsDNyW0Cg2lsEIiVJ0OldErViVQaIWpg1AlNnYZSCcrQIqL0I0fQ=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: hsSCsDpwwC29qkrhlKZt6n/g/fOLnEOjp5q7K1mr3aue/X2vQBxbkeTwBAlaYc/ZSN5SvXbjTVfaNHSGQt/G6DiG/tMYCty9DkFy8R4vxkbrn0cy/C3mDF1GPGvyprIOPHZGc8p6MbKn+VibXC8ydxo1IikPAKAevnRUVP9czds=
sudo: false
